### ISSUE TITLE
Problem with weighted_maximum and */1

### ISSUE THREAD

**Issue by stevana** [triska/clpb#1]
Given the following:

```prolog
works(A, B) :-
    sat(*([+[A, B], B])),
    labeling([A, B]).

doesnt(A, B) :-
    sat(*([+[A, B], B])),
    weighted_maximum([-1,-1], [A, B], _).

works2(A, B) :-
    sat(A + B * B),
    weighted_maximum([-1,-1], [A, B], _).
```

running `doesnt` throws the following error:

```
[debug]  ?- doesnt(A, B).
ERROR: Uninstantiated argument expected, found 1
ERROR: In:
ERROR:   [19] throw(error(uninstantiation_error(1),_11940))
ERROR:   [18] error:uninstantiation_error(1) at /usr/lib/swi-prolog/library/error.pl:161
ERROR:   [17] error:is_not(var,1) at /usr/lib/swi-prolog/library/error.pl:282
ERROR:   [16] error:element_is_not([1],var) at /usr/lib/swi-prolog/library/error.pl:324
ERROR:   [15] error:element_is_not([_12080,1],var) at /usr/lib/swi-prolog/library/error.pl:321
ERROR:   [14] error:not_a_list(list(var),[_12128,1]) at /usr/lib/swi-prolog/library/error.pl:304
ERROR:   [13] error:is_not(list(var),[_12176,1]) at /usr/lib/swi-prolog/library/error.pl:270
ERROR:   [12] error:must_be(list(var),[_12224,1]) at /usr/lib/swi-prolog/library/error.pl:248
ERROR:   [11] clpb:weighted_maximum([-1,-1],[_12282,1],_12266) at /usr/lib/swi-prolog/library/clp/clpb.pl:1442
ERROR:   [10] doesnt(_12314,1) at ...
ERROR:    [9] <user>
   Exception: (12) error:must_be(list(var), [_9118{...}, 1]) ? creep
   Exception: (11) clpb:weighted_maximum([-1, -1], [_9118{...}, 1], _12538) ? creep
   Exception: (10) doesnt(_8658, _8660) ? creep
```

while `works` and `works2` both work, which seems odd to me, but perhaps I'm misunderstanding something?

**Comment by triska** [comment]
We have:

<pre>
<b>?- sat(*([+[A, B], B])).</b>
   B = 1, clpb:sat(A=:=A)
;  false.
</pre>

Notice `B = 1`. So, when `weighted_maximum/2` is invoked, the second argument is not a list of *variables*.

**Comment by stevana** [comment]
I see, that explains the error message.

But why does `works` work (I can see my mistake in `works2` now)? `labeling` also seems to take a list of variables?

**Comment by triska** [comment]
In `labeling/1`, there is no requirement that the elements be *variables*: They can also be concrete Boolean values.

I can generalize `weighted_maximum/2` to also allow this. However, this makes the code a bit more complicated, so in this case I have so far avoided this.

**Comment by stevana** [comment]
I see, I naively assumed I could list all concrete solutions with `labeling/1` and then filter out the "best" ones using `weighted_maximum/2`. In particular I'm interested in the "minimal" solution (that uses the least variables).

If there's another way to achieve this I'm happy to do that instead, but I couldn't think of a way to.

**Comment by triska** [comment]
`weighted_maximum/2` cannot filter variables, it only assigns `0` or `1` to the given variables.

To actually minimize the variables, you have to reconsider the approach. For example, it may work to build a different kind of SAT instance that uses `0` to denote that a specific variable is *not* taken, and then to maximize (or minimize) over these "indicator variables".

**Comment by stevana** [comment]
Sorry, I meant: minimise the *amount* of variables used. `weighted_maximum` with all weights being `-1` seems to do the trick.

Here solutions with 1-3 variables being true are shown:

```prolog
?- sat(X+Y+Z), labeling([X, Y, Z]).
X = Y, Y = 0,
Z = 1 ;
X = Z, Z = 0,
Y = 1 ;
X = 0,
Y = Z, Z = 1 ;
X = 1,
Y = Z, Z = 0 ;
X = Z, Z = 1,
Y = 0 ;
X = Y, Y = 1,
Z = 0 ;
X = Y, Y = Z, Z = 1
```

while here:

```prolog
sat(X+Y+Z), weighted_maximum([-1, -1, -1], [X, Y, Z], _).
X = Y, Y = 0,
Z = 1 ;
X = Z, Z = 0,
Y = 1 ;
X = 1,
Y = Z, Z = 0.
```

We only see solutions where one variable is true.

**Comment by triska** [comment]
OK, then it seems easy enough: Simply remove the integers from the list of variables so that only the variables remain, and then apply `weighted_maximum/2` with all coefficients specified as&nbsp;`-1`.

Does that work for you?

**Comment by stevana** [comment]
Ah yes, thank you!
